<?php

namespace App\Services;

use Illuminate\Support\Collection;

class ExportImportHelper
{
    /**
     * Export data ke CSV/Excel format
     */
    public static function exportCsv(string $filename, array $headers, Collection $rows, callable $rowCallback)
    {
        $responseHeaders = [
            'Content-Type' => 'text/csv; charset=UTF-8',
            'Content-Disposition' => 'attachment; filename=' . $filename . '_' . date('Y-m-d') . '.csv',
        ];

        $callback = function() use ($headers, $rows, $rowCallback) {
            $file = fopen('php://output', 'w');
            
            // Add UTF-8 BOM for proper Excel encoding
            fprintf($file, chr(0xEF).chr(0xBB).chr(0xBF));
            
            fputcsv($file, $headers);
            
            foreach ($rows as $row) {
                fputcsv($file, $rowCallback($row));
            }
            
            fclose($file);
        };

        return response()->stream($callback, 200, $responseHeaders);
    }

    /**
     * Export data ke print/PDF format
     */
    public static function exportPdf(string $title, array $headers, array $rows)
    {
        $html = '<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>' . htmlspecialchars($title) . '</title>
    <style>
        body { font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; font-size: 13px; color: #333; margin: 30px; }
        h1 { font-size: 24px; color: #1e293b; margin-bottom: 5px; }
        .date { font-size: 11px; color: #64748b; margin-bottom: 20px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th { background-color: #f1f5f9; color: #1e293b; font-weight: bold; text-align: left; border-bottom: 2px solid #cbd5e1; }
        th, td { padding: 10px 12px; border-bottom: 1px solid #e2e8f0; }
        tr:nth-child(even) { background-color: #f8fafc; }
        .footer { margin-top: 40px; text-align: center; font-size: 11px; color: #94a3b8; border-top: 1px solid #e2e8f0; padding-top: 10px; }
        @media print {
            .no-print { display: none; }
        }
    </style>
</head>
<body>
    <div class="no-print" style="margin-bottom:20px; text-align:right;">
        <button onclick="window.print()" style="padding:8px 16px; background-color:#3b82f6; color:white; border:none; border-radius:6px; cursor:pointer; font-weight:bold;">Print / Save as PDF</button>
    </div>
    <h1>' . htmlspecialchars($title) . '</h1>
    <div class="date">Exported on: ' . date('Y-m-d H:i:s') . '</div>
    <table>
        <thead>
            <tr>';
        foreach ($headers as $header) {
            $html .= '<th>' . htmlspecialchars($header) . '</th>';
        }
        $html .= '</tr>
        </thead>
        <tbody>';
        foreach ($rows as $row) {
            $html .= '<tr>';
            foreach ($row as $col) {
                $html .= '<td>' . htmlspecialchars($col ?? '—') . '</td>';
            }
            $html .= '</tr>';
        }
        $html .= '</tbody>
    </table>
    <div class="footer">Generated by SupplyGuard Risk Intelligence Platform &copy; ' . date('Y') . '</div>
    <script>
        // Auto trigger browser print window
        window.onload = function() { window.print(); }
    </script>
</body>
</html>';

        return response($html)->header('Content-Type', 'text/html');
    }
}
